spring:
  jpa:
    show-sql: true  # ??? ?? ?? ??
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect  # mysql?? ??
  h2:
    console:
      enabled: true
  profiles:
    include: oauth  # application-oauth ?? ??